In [1]:
import numpy as np
print("numpy lib imported")

numpy lib imported


In [2]:
#check version for numpy:
print(np.__version__)

1.26.4


In [3]:
a1=np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# create list and pass float datatypes:
list=[1,2,3,4,5,6]
a3=np.array([1,2,3,4,5,6])
print(a3)
print(type(a3))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
# 2d aaray(2 dimentional aaray):--
# create 2D aaray
a3=np.array([[1,2,3,4],[5,6,7,8]])
print(a3)
print(type(a3))
a3.shape

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


(2, 4)

In [14]:
#attribute
#Shape
#ndim
#dtype
#itemsize
#nbtypes
print(a3.ndim)
print(a3.shape)
print(a3.dtype)
print(a3.itemsize)
print(a3.nbytes)

2
(2, 4)
int32
4
32


In [18]:
# create float type 2-D aaray of float type 3*3 , print all attributes
a4=np.array([[4.4,5.6,7.6],[4.3,5.8,9.6],[4.2,5,8]])
print(a4.ndim)
print(a4.shape)
print(a4.dtype)
print(a4.itemsize)
print(a4.nbytes)

2
(3, 3)
float64
8
72


In [20]:
a5=np.array([['banana','apple123'],['pen','pencil']])
print(a5)
print(a5.ndim)
print(a5.shape)
print(a5.dtype)
print(a5.itemsize)
print(a5.nbytes)

[['banana' 'apple123']
 ['pen' 'pencil']]
2
(2, 2)
<U8
32
128


In [21]:
import numpy as np

In [23]:
distance=np.array([10,20,30,40,50,])
time=np.array([0.3,0.4,0.5,0.6,0.7])
print(distance)
print(time)

[10 20 30 40 50]
[0.3 0.4 0.5 0.6 0.7]


In [4]:
import numpy as np

In [5]:
# 3 Dimentional array(3d array):--
a6=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(a6)
print(a6.shape)
print(a6.ndim)
print(a6.dtype)
print(a6.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
(2, 2, 3)
3
int32
12
