In [2]:
import numpy as np
import pandas as pd

In [3]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.transpose() #it converts row into column

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
a.flatten()  #it converts array into one dimention

array([1, 2, 3, 4, 5, 6])

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
a

array([1, 2, 3])

In [8]:
np.concatenate((a,b,c))  #use to join tow aaray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [10]:
a.fill(2)
a

array([2, 2, 2])

In [11]:
#what is slicing =it is used to fetch element from array always having(start,stop,step)

In [6]:
a=np.array([10,20,30,40,50,60])   #slicing[10,20,30,40,50] ==>(positiv indexing from 0,1,2,3,4...  & negative from -1,-2,-3,-4,...)
a

array([10, 20, 30, 40, 50, 60])

In [13]:
a[0:2]

array([10, 20])

In [14]:
a[0]

10

In [15]:
a[3]

40

In [10]:
a[-1:-5:-2]

array([60, 40])

In [17]:
a.sum()

150

In [18]:
b.sum()

15

In [19]:
c=np.array([[1,2],[4,5]])
c

array([[1, 2],
       [4, 5]])

In [20]:
d=np.array([[5,6],[9,10]])
d

array([[ 5,  6],
       [ 9, 10]])

In [21]:
np.concatenate((c,d),axis=0) #axis =0 keeps columns constant and no. of rows is added

array([[ 1,  2],
       [ 4,  5],
       [ 5,  6],
       [ 9, 10]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 1,  2,  5,  6],
       [ 4,  5,  9, 10]])

In [24]:
c.min()

1

In [25]:
c.max()

5

In [27]:
c.mean()

3.0

In [28]:
c*10

array([[10, 20],
       [40, 50]])

In [29]:
c/10

array([[0.1, 0.2],
       [0.4, 0.5]])

In [30]:
c+10

array([[11, 12],
       [14, 15]])

In [33]:
c=np.arange(0,3).reshape(3,1)
c

array([[0],
       [1],
       [2]])